# Generated by Django 2.0.5 on 2018-06-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='NICKNAME')),
                ('likey', models.CharField(blank=True, max_length=50, verbose_name='LIKEY')),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pic', verbose_name='PROFILE_PICTURE')),
            ],
        ),
    ]
